version: "3.3"
services:
  nsqd-1:
    image: nsqio/nsq
    command: nsqd -broadcast-address nsqd-1 -lookupd-tcp-address nsqlookupd-1:4160 -lookupd-tcp-address nsqlookupd-2:4160
  nsqd-2:
    image: nsqio/nsq
    command: nsqd -broadcast-address nsqd-2 -lookupd-tcp-address nsqlookupd-1:4160 -lookupd-tcp-address nsqlookupd-2:4160
  nsqlookupd-1:
    image: nsqio/nsq
    command: nsqlookupd -broadcast-address nsqlookupd-1
  nsqlookupd-2:
    image: nsqio/nsq
    command: nsqlookupd -broadcast-address nsqlookupd-2
  nsqadmin:
    image: nsqio/nsq
    command: nsqadmin -lookupd-http-address nsqlookupd-1:4161 -lookupd-http-address nsqlookupd-2:4161
  node-server:
    image: node:8-alpine
    volumes:
      - .:/opt
    command: node /opt/test.js
  node-test:
    image: node:8-alpine
    volumes:
      - .:/opt
    command: node /opt/server.js
